// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp3gPrep59uPSr62Zu5A_PRGggwxB91qA',
    appId: '1:69674030754:web:064ff6f7e98198070f29fb',
    messagingSenderId: '69674030754',
    projectId: 'apiit-cms',
    authDomain: 'apiit-cms.firebaseapp.com',
    storageBucket: 'apiit-cms.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDItGh_mTvTIm2sSZWmIxzsmGElNsGFFC8',
    appId: '1:69674030754:android:cfd65a6a391f1bbf0f29fb',
    messagingSenderId: '69674030754',
    projectId: 'apiit-cms',
    storageBucket: 'apiit-cms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBe_iAAEjYyOpX5PC6fKCkpC2mKNVc1z4',
    appId: '1:69674030754:ios:4f1f7962888cb18a0f29fb',
    messagingSenderId: '69674030754',
    projectId: 'apiit-cms',
    storageBucket: 'apiit-cms.firebasestorage.app',
    iosBundleId: 'com.example.apiitCms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBe_iAAEjYyOpX5PC6fKCkpC2mKNVc1z4',
    appId: '1:69674030754:ios:4f1f7962888cb18a0f29fb',
    messagingSenderId: '69674030754',
    projectId: 'apiit-cms',
    storageBucket: 'apiit-cms.firebasestorage.app',
    iosBundleId: 'com.example.apiitCms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp3gPrep59uPSr62Zu5A_PRGggwxB91qA',
    appId: '1:69674030754:web:a0159cd319a0f2c40f29fb',
    messagingSenderId: '69674030754',
    projectId: 'apiit-cms',
    authDomain: 'apiit-cms.firebaseapp.com',
    storageBucket: 'apiit-cms.firebasestorage.app',
  );
}
